### ISSUE TITLE
Add Fluent Api to work with for most cases

### ISSUE THREAD

**Issue by hofmanndavid** [JarekToro/responsive-layout#1]
Given the next rules of current API usage
- A ResponsiveLayout is supposed to contain only ResponsiveRow components
- A ResponsiveRow component can contain only ResponsiveColumn elements. 
- A ResponsiveColumn component can only contain a single component inside it with it's configured widths on each predefined size

Then a fluent-like api can be created to simplify the usage of the 3 main clases of this responsive layout.

Some quick-n-dirty examples

```
ResponsiveLayout rl = RL.makeNew()
   .addRow(RL.newRow()
                          // 0 means hidden, and optional alignment overload
                          .addColumn(0,12,6,6, grid, Alighnment.BOTTOM_RIGHT)
                          .addColumn(0,12,6,6, filterButton)
                     ).
   .addRow(RL.newRow()
                          .addColumn(0,12,6,6, newButton)
                          .addColumn(0,12,6,6, editButton)
                     )
     );
setContent(rl);

```

Just an initial idea, this should be worked out.

**Comment by Jayrok94** [comment]
See the recently opened ConvenienceAPI Branch assigned for this issue

````java
ResponsiveRow row = responsiveLayout.addRow()
                .withAlignment(Alignment.MIDDLE_CENTER)
                .withMargin(true);

 ResponsiveColumn column = row()
                .withDisplayRules(12, 3, 12, 12)
                .withVisibilityRules(false, true, true, true)
                .withComponent/*button etc*/);
````

**Comment by hofmanndavid** [comment]
Makes sense Jarek. Excelent work. I guess I will be helping next weekend with this. In the meantime as long as the addon is marked as experimental this convenience API can be released with some release notes explaining that you want feedback on the early idea and that the API will most surely change.
