### ISSUE TITLE
Provide a 'fixed width' container

### ISSUE THREAD

**Issue by bassmartin** [JarekToro/responsive-layout#12]
In Twitter Bootstrap, the default container has a maximum width (it won't fill the width on huge screens).

> Use .container for a responsive fixed width container.
> Use .container-fluid for a full width container, spanning the entire width of your viewport.
ref: http://getbootstrap.com/css/#overview-container

> Container width	    None (auto)	    750px	         970px	      1170px

This allow applications to be centered on big screens (like Facebook for example)

Is that something you would consider adding to the library?

**Comment by JarekToro** [comment]
Yes and this is already in development at the moment will be released soon.

**Comment by JarekToro** [comment]
API
```java
ResponsiveLayout responsiveLayout = new ResponsiveLayout(ContainerType)
responsiveLayout.setContainerType(ContainerType)
```

ContainerType.FLUID || FIXED

**Comment by bassmartin** [comment]
The container is not center. It kind of more on the left side...

**Comment by bassmartin** [comment]
Found why, my fault.
You changed the default behaviour of ```addColumn()``` when no ```displayRules``` are set and this led to the container not being drawn in the center.

I added ```withDisplayRules(12,12,12,12)``` where I was assuming the 'default' behaviour and it shows in the center properly.

👍

**Comment by bassmartin** [comment]
Small note about this change:

When defining nested ```ResponsiveLayout``` objects, they need to be created with ```ContainerType.FLUID``` or the UI won't draw properly. ;-)

**Comment by JarekToro** [comment]
Thanks! Moved this to separate issue #15
