### ISSUE TITLE
Provide a 'withRightComponent' method

### ISSUE THREAD

**Issue by bassmartin** [JarekToro/responsive-layout#13]
There is currently a way to center a component in a column with the `withCenteredComponent` method. 

I would like to have something similar to push the component at the far right of the column. I could then put that 'menu button' at the right end of a phone screen
<img width="319" alt="screen shot 2016-10-26 at 15 05 33" src="https://cloud.githubusercontent.com/assets/10145772/19741204/ca47a1ae-9b8d-11e6-839c-ab58e8414fcf.png">

Thanks.

**Comment by JarekToro** [comment]
API 
```java
col.setAlignment(ColumnComponentAlignment)
col.withCenteredComponent(Component)
col.withRightAlignedComponent(Component)
```

**Comment by bassmartin** [comment]
Worked for me 👍

**Comment by hofmanndavid** [comment]
IMHO

col.withComponent(component); // default alignment
col.withComponent(component, alignment); 
that api should replace the alignment, centered and rightAligned methods....

**Comment by JarekToro** [comment]
I think your correct @hofmanndavid 

Sorry for the `super.lateReponse()`

**Comment by JarekToro** [comment]
@hofmanndavid methods were added
