### ISSUE TITLE
Conditional margins

### ISSUE THREAD

**Issue by bassmartin** [JarekToro/responsive-layout#14]
I would like to be able to specify for which screen size a margin is to be applied.

For example, I would like to have a margin between my menu and content on big screen, but I don't want it on phones to keep screen space for content.

What do you think?

**Comment by JarekToro** [comment]
I think this will be very useful. Just need a clean API for this feature

**Comment by JarekToro** [comment]
Master Branch implements this.

`.withMargin(ResponsiveRow.MarginSize.NORMAL, ResponsiveColumn.DisplaySize.XS, true)`

now setting 

'withMargin(true)`

does this 

```java
`.setMargin(ResponsiveRow.MarginSize.NORMAL, ResponsiveColumn.DisplaySize.XS, true)`
`.setMargin(ResponsiveRow.MarginSize.NORMAL, ResponsiveColumn.DisplaySize.SM, true)`
`.setMargin(ResponsiveRow.MarginSize.NORMAL, ResponsiveColumn.DisplaySize.MD, true)`
`.setMargin(ResponsiveRow.MarginSize.NORMAL, ResponsiveColumn.DisplaySize.LG, true)`
```

because now each displaySize Margin must be explicitly set.
