### ISSUE TITLE
setScrollable(true) has no effect

### ISSUE THREAD

**Issue by initialflame** [JarekToro/responsive-layout#19]
If i set the Responsive layout to scrollable using this Method

`responsiveLayout.setScrollable(true)`

No Scrollbar apears. When i have some Panels inserted to the RepsoniveLayout wich becomes bigger if the screen is smaller.

Maybe you have a solution

**Comment by JarekToro** [comment]
Would it be possible for you to post some code?

The setScrollable should allow the responsivelayout to scroll if it's contents and larger then the size of the screen.

**Comment by JarekToro** [comment]
Closing. Will reopen if this receives further info.
