### ISSUE TITLE
Wrap css from flexboxgrid inside a prefix using SASS

### ISSUE THREAD

**Issue by hofmanndavid** [JarekToro/responsive-layout#2]
This will improve the maintainability of the code as we will be using our own pre-fixed styles.

**Comment by JarekToro** [comment]
This requires that the add-on compile its own widget-set. Though this would be a nice feature allowing users to set there own variables like spacing and margin at compile time. At this time this issue will be open to anyone with more experience in the add-on creation process. As it stands the Add-on does not have its own widget-set.

Here is a nice article about adding scss to an Add-on
https://vaadin.com/wiki/-/wiki/Main/Packaging+SCSS+or+CSS+in+an+add-on


Thanks.

**Comment by JarekToro** [comment]
Closing this because the Css is created by Scss but it still Isn't packaged as Scss when submitted the Add-on which will be a separate issue.
