### ISSUE TITLE
Potential CSS class clashing with Twitter Bootstrap

### ISSUE THREAD

**Issue by bassmartin** [JarekToro/responsive-layout#20]
I have another project that already exists and uses Twitter Bootstrap. I'm migrating this app to be completely on Vaadin and I want to use this responsive layout plugin. But, the HTML generated is all twisted since this plugin and Twitter Bootstrap uses the same CSS class names.

Do you any idea how I could make them work together?

Thanks.

**Comment by JarekToro** [comment]
Are you running 1.3? I prefixed the class names there.

**Comment by bassmartin** [comment]
I tried on 1.2 I'm pretty sure. I will give it a try soon with 1.3 I think that would work.

**Comment by JarekToro** [comment]
@bassmartin  was this resolved?

**Comment by bassmartin** [comment]
Still had no time to check it out. I hope I can early next week, sorry for the delays.

**Comment by JarekToro** [comment]
Closing issue as it's resolved from my testing, will open again if issue persist.

**Comment by bassmartin** [comment]
Just tested and it works. Thanks.
