### ISSUE TITLE
Increase precision to CSS class to correct wrong behaviour

### ISSUE THREAD

**Issue by eRfO** [JarekToro/responsive-layout#25]
We have to add these CSS classes to fix a wrong behaviour with some display resolutions:

```
@media only screen and (min-width: 75em) {
  .rl-col-lg-2 {
    -ms-flex-preferred-size: 16.66666667%;
    flex-basis:16.66666667%;
    max-width: 16.66666667%;
  }
}

@media only screen and (min-width: 62em) {
  .rl-col-md-2 {
    -ms-flex-preferred-size: 16.66666667%;
    flex-basis: 16.66666667%;
    max-width: 16.66666667%;
  }
}

@media only screen and (min-width: 48em) {
  .rl-col-sm-2 {
    -ms-flex-preferred-size: 16.66666667%;
    flex-basis: 16.66666667%;
    max-width: 16.66666667%;
  }
}
```

**Comment by JarekToro** [comment]
Thank you for the code fixes, what is the "wrong behavior" your experiencing

**Comment by JarekToro** [comment]
@eRfO I would like to add this. I just need a description of what had how this fixes it.

**Comment by JarekToro** [comment]
Closing for now. @eRfO feel free to comment back id love to know more.

**Comment by eRfO** [comment]
@JarekToro i post 2 images that show the wrong behavior. The first image is an example without the fix while the second show the right behavior.

![without-fix](https://cloud.githubusercontent.com/assets/3831236/21605021/c0212228-d1a6-11e6-8755-978a36a3f484.png)
![with-fix](https://cloud.githubusercontent.com/assets/3831236/21605027/c5def92e-d1a6-11e6-8146-43606afeb110.png)

**Comment by JarekToro** [comment]
Perfect thank you.

**Comment by JarekToro** [comment]
Added and tested code. Thanks again. I will upload to Vaadin Directory soon and close this after.

**Comment by JarekToro** [comment]
Apologizes on the extremely long delay.

Fixed in latest release. Now on Vaadin Directory
