### ISSUE TITLE
BasicFullPageUI.java is not working as expected

### ISSUE THREAD

**Issue by pk1057** [JarekToro/responsive-layout#28]
Hello,
i tried your fantastic library and had big trouble to get the BasicFullPageUI running as expected.
It always showed up only with two button lines and not like described in the wiki.

So a compared the wiki and the test source code and found out that at the end of the init method
the file creates a panel and does a second setContent on the main layout overwriting the responsive layout.

When i removed this second setContent everything works as expected !

```
        setContent(responsiveLayout);

        Panel panel = new Panel("Panel");
-->         setContent(panel);
        ResponsiveLayout layout = new ResponsiveLayout(ResponsiveLayout.ContainerType.FLUID);
        panel.setContent(layout);
        layout.addRow()
                .withMargin(ResponsiveRow.MarginSize.SMALL)
                .withVerticalSpacing(ResponsiveRow.SpacingSize.SMALL, true)
                .withHorizontalSpacing(true)
                .addColumn().withDisplayRules(12, 12, 12, 12).setComponent(new Label("Test"));


    }
```

**Comment by JarekToro** [comment]
Ah yes, thank you during last revision I was messing around with that page trying something and I forgot to put it back! Thanks for the heads up!

**Comment by JarekToro** [comment]
Fixed in latest release. Now on Vaadin Directory
