### ISSUE TITLE
Vertical alignment

### ISSUE THREAD

**Issue by bassmartin** [JarekToro/responsive-layout#29]
Is there a way to set vertical alignment?

Here is what my UI looks like
<img width="286" alt="screen shot 2017-02-08 at 09 54 13" src="https://cloud.githubusercontent.com/assets/10145772/22742433/b99c3604-ede4-11e6-99d9-d0194b914599.png">

I would like the button to be pushed down so it aligns with the combo box.

```
        ResponsiveLayout layout = new ResponsiveLayout()
        layout.addRow().withSpacing(true).with {
            ...
            addColumn().withDisplayRules(12, 12, 2, 2).withComponent(clientConfig)
            addColumn().withDisplayRules(12, 12, 2, 2).withComponent(toolbar)
        }
```

Thanks.

**Comment by JarekToro** [comment]
The row has a set alignment method you can try Bottom_left
Of Middle_left enums

**Comment by bassmartin** [comment]
Works like a charm. Thanks again Jarek!

**Comment by galcyurio** [comment]
For future visitors.
Maybe method has been replaced.
````java
ResponsiveRow.setDefaultComponentAlignment()
````
