### ISSUE TITLE
Research better object composition

### ISSUE THREAD

**Issue by hofmanndavid** [JarekToro/responsive-layout#3]
Instead of extending CssLayout, maybe we can compose out object to use them. 
By doing this we don't inherit the behaviour of CssLayout and provide a cleaner api. 

I guess we should implement a more generic vaadin Layout Interface.

**Comment by Jayrok94** [comment]
CssLayout is the lowest level layout with out having to build your own connectors. We can wrap the class to hide csslayout implementation maybe?

**Comment by JarekToro** [comment]
Closing and Opening "Use GWT to Create Layout Classes"
