### ISSUE TITLE
convenience methods withStyleName

### ISSUE THREAD

**Issue by derBertW** [JarekToro/responsive-layout#30]
Not a real issue but might make the code looks nicer: For sass styling I add custom style classes to rows and columns and nested layouts as well. Would be nice if I could just write
`addColumn().withDisplayRules(...).withStyleName("mycolumn")...`

**Comment by JarekToro** [comment]
This sounds like a nice addition.

I'm not sure when I could get to it just yet. But if a PR was submitted before then I would accept it and upload it ASAP.

Thanks.
