### ISSUE TITLE
make ResponsiveColumn implement SingleComponentContainer

### ISSUE THREAD

**Issue by derBertW** [JarekToro/responsive-layout#33]
If `ResponsiveColumn` would implement `com.vaadin.ui.SingleComponentContainer` it could be used as Container for `com.vaadin.navigator` and probably other purposes. 
pro: could easily be implemented - no new functionality
con: bit more messy API (two methods for same purpose e.g. `setContent` and `setComponent`)

**Comment by JarekToro** [comment]
I agree that's a good idea. I'm working on making this layout a little more of a first class citizen instead of subclasses of csslayout. In the meantime if you submitted a PR I would accept it and upload to vaadin.

**Comment by JarekToro** [comment]
I didn't realize it was you @derBertW don't feel you need to submit a pull request. lol I don't want you to feel every issue needs to be someone else's pull request lol

**Comment by derBertW** [comment]
That is perfectly allright. I was already working on this when I filed the
issue. It is actually already done but I have to look a bit deeper into
this ComponentAttachDetachNotifier which is part of the container. When I'm
feeling ok with my solution I'll submit the PR and you can review it.

best regards,
Bert.


2017-03-09 3:24 GMT+01:00 Jarek Toro <notifications@github.com>:

**Comment by JarekToro** [comment]
You the man

**Comment by JarekToro** [comment]
Updated and now on the Vaadin Directory
https://vaadin.com/directory#!addon/responsive-layout
