### ISSUE TITLE
Plans for Vaadin 8

### ISSUE THREAD

**Issue by nioe** [JarekToro/responsive-layout#40]
Hi Jarek

Are there any plans to upgrade from Vaadin 7 to 8?
We're using your library in a Vaadin 8 Project currently which worked fine so far. But now we wanted to extend the ResponsiveColumn and get compilation errors.

Thanks a lot for your answer and at this point thank you for your great work as well!

Cheers, Nick

**Comment by JarekToro** [comment]
Sorry for delay.

Thanks again for the contribution!


It has been uploaded to the Vaadin Directory

**Comment by nioe** [comment]
Thanks a lot for your effort! Have a good week!
