### ISSUE TITLE
Uncaught SyntaxError: Invalid or unexpected token

### ISSUE THREAD

**Issue by daoudabeye** [JarekToro/responsive-layout#42]
When using vaadin 8.1, i'm getting this error:
Uncaught SyntaxError: Invalid or unexpected token

**Comment by JarekToro** [comment]
Can you send me the full log

**Comment by daoudabeye** [comment]
Please find print screen below

![issue](https://user-images.githubusercontent.com/12284053/29003346-d7f2c834-7aac-11e7-9bb9-f92f39d6f0a7.png)

**Comment by daoudabeye** [comment]
It happen only when using VerticalStepper.
List<Step> steps = Arrays.asList(serviceStep, operationStep, executionStep);
		VerticalStepper stepper = new VerticalStepper(steps, true);
		stepper.setSizeFull();
		stepper.start();

**Comment by JarekToro** [comment]
Remove the set size full and see if that resolves it.

**Comment by daoudabeye** [comment]
Hi,
i could solve it.
Thanks.
