### ISSUE TITLE
how should be to use it?

### ISSUE THREAD

**Issue by webshopboys** [JarekToro/responsive-layout#60]
Hi,

I tried in V8.4.3 with annotated UI and created nested example. Filled layout to a modal resizable window but nothing happened when resized.
I missed css (not required by docs) or how should be to use it?

Thanks,
Karl

@Viewport("width=device-width, initial-scale=1")
public class MyUI extends UI {
....
 private void tryResponsive() {
        Window dialog = new Window("Responsive - resize it");
        Component layout = PopupUI.getLayout2();
        layout.setSizeFull();
        dialog.setContent(layout);
        dialog.setResizable(true);
        ui.addWindow(dialog);
    }
 public static Component getLayout2() {
        ResponsiveLayout responsiveLayout = new ResponsiveLayout();
        ResponsiveRow row = responsiveLayout.addRow();

        row.addColumn().withDisplayRules(12, 6, 4, 4).withComponent(createNestedLayout());
        row.addColumn().withDisplayRules(12, 6, 4, 4).withComponent(createNestedLayout());
        row.addColumn().withDisplayRules(12, 6, 4, 4).withComponent(createNestedLayout());

        return responsiveLayout;

    }

    public static ResponsiveLayout createNestedLayout() {
        ResponsiveLayout nestedLayout = new ResponsiveLayout();
        ResponsiveRow nestedLayoutRow = nestedLayout.addRow();

        Label label = new Label("Title!");
        label.setSizeFull();

        Button button = new Button("", FontAwesome.ANCHOR);
        button.addStyleName(ValoTheme.BUTTON_PRIMARY);
        button.setSizeFull();

        TextField field = new TextField();
        field.setPlaceholder("Description");
        field.setSizeFull();

        nestedLayoutRow.addColumn().withDisplayRules(12, 6, 4, 4).withComponent(label);
        nestedLayoutRow.addColumn().withDisplayRules(12, 6, 4, 4).withComponent(button);
        nestedLayoutRow.addColumn().withDisplayRules(12, 6, 4, 4).withComponent(field);

        return nestedLayout;
    }

![image](https://user-images.githubusercontent.com/1469654/41986501-9d5c97d8-7a36-11e8-9b40-bc316f89b1e0.png)

![image](https://user-images.githubusercontent.com/1469654/41986516-afc354fc-7a36-11e8-8bd1-541f9bb45fa6.png)

![image](https://user-images.githubusercontent.com/1469654/41986554-c5e09b6e-7a36-11e8-81f1-b5139dd4a246.png)

**Comment by JarekToro** [comment]
This works on the browser window resized not vaddin windows

**Comment by webshopboys** [comment]
Hello,
interesting. It works on UI and not in Window.

**Comment by JarekToro** [comment]
Responsive design is design that responds to the size of the browser.

**Comment by webshopboys** [comment]
OK, works well on main UI, thank you.
